#!/usr/bin/env python3
"""Generate 360x360 needle assets and LVGL C files for Waveshare ESP32-S3-LCD-1.85.

Single source of truth: artwork/build/geometry_360.json.
Uses PIL with 8x supersampling for antialiased needle and shadow rendering.
Produces:
  - artwork/build/needle_360_accu.png
  - artwork/build/needle_360_accu_shadow.png
  - artwork/build/needle_360_brake.png
  - artwork/build/needle_360_brake_shadow.png
  - artwork/build/test_composite_360.png
  - firmware/accu_panel_185/gauge_geometry.h
  - firmware/accu_panel_185/img_dial_face.c
  - firmware/accu_panel_185/img_needle_accu.c
  - firmware/accu_panel_185/img_needle_accu_shadow.c
  - firmware/accu_panel_185/img_needle_brake.c
  - firmware/accu_panel_185/img_needle_brake_shadow.c
"""

import os
import json
import math
from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
BUILD = os.path.join(HERE, "build")
FW_DEST = os.path.join(os.path.dirname(HERE), "firmware", "accu_panel_185")

os.makedirs(BUILD, exist_ok=True)
os.makedirs(FW_DEST, exist_ok=True)

GEOM_PATH = os.path.join(BUILD, "geometry_360.json")
with open(GEOM_PATH, "r", encoding="utf-8") as f:
    GEOM = json.load(f)

ACCU = GEOM["scales"]["accum"]
BRAKE_L = GEOM["scales"]["brake_l"]
BRAKE_R = GEOM["scales"]["brake_r"]

NEEDLE_COLOR = (194, 198, 202, 255)       # #c2c6ca
NEEDLE_EDGE_COLOR = (88, 91, 94, 255)     # subtle dark border

SHADOW_DX = 3
SHADOW_DY = 4


def generate_needle(length, boss_r, width, tip_w=3.5, shadow=False):
    """Draw a spade-style needle pointing UP, pivot at bottom centre.
    
    Uses 8x supersampling for subpixel edge quality.
    """
    scale = 8
    w_px = int(math.ceil(width + 6))
    if w_px % 2 == 0:
        w_px += 1
    h_px = int(math.ceil(length + 4))
    
    px = w_px / 2.0
    py = length + 1.0
    
    # 8x super-sampled canvas
    sw = w_px * scale
    sh = h_px * scale
    spx = px * scale
    spy = py * scale
    
    s_len = length * scale
    s_w = width * scale
    s_tip = tip_w * scale
    s_boss = boss_r * scale
    
    root_y = spy - (s_boss - 3.0 * scale)
    shoulder_y = spy - (s_len * 0.66)
    tip_y = spy - s_len
    
    pts = [
        (spx - s_w / 2.0, root_y),
        (spx - s_w / 2.0, shoulder_y),
        (spx - s_tip / 2.0, tip_y),
        (spx + s_tip / 2.0, tip_y),
        (spx + s_w / 2.0, shoulder_y),
        (spx + s_w / 2.0, root_y),
    ]
    
    img_large = Image.new("RGBA", (sw, sh), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img_large)
    
    if shadow:
        for grow, alpha in ((2.2 * scale, 45), (1.1 * scale, 60), (0.0, 90)):
            s_pts = []
            for x, y in pts:
                dx = grow if x > spx else -grow
                s_pts.append((x + dx, y))
            draw.polygon(s_pts, fill=(0, 0, 0, alpha))
    else:
        # Outer edge
        draw.polygon(pts, fill=NEEDLE_EDGE_COLOR)
        
        # Inset fill
        inset = 1.0 * scale
        inner_pts = [
            (spx - s_w / 2.0 + inset, root_y),
            (spx - s_w / 2.0 + inset, shoulder_y),
            (spx - s_tip / 2.0 + inset * 0.4, tip_y + inset),
            (spx + s_tip / 2.0 - inset * 0.4, tip_y + inset),
            (spx + s_w / 2.0 - inset, shoulder_y),
            (spx + s_w / 2.0 - inset, root_y),
        ]
        draw.polygon(inner_pts, fill=NEEDLE_COLOR)
    
    resampled = img_large.resize((w_px, h_px), Image.Resampling.LANCZOS)
    return resampled, w_px, h_px, int(px), int(round(py))


def rgb565(r, g, b) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def convert_to_lvgl_c(im: Image.Image, symbol: str, alpha: bool, comment: str) -> str:
    w, h = im.size
    px = im.load()
    
    data = bytearray()
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if not alpha:
                r = r * a // 255
                g = g * a // 255
                b = b * a // 255
            c = rgb565(r, g, b)
            data.append(c & 0xFF)
            data.append((c >> 8) & 0xFF)
            if alpha:
                data.append(a)
                
    cf = "LV_IMG_CF_TRUE_COLOR_ALPHA" if alpha else "LV_IMG_CF_TRUE_COLOR"
    
    lines = [
        f"// GENERATED by make_360_assets.py: {comment}",
        "#include <lvgl.h>",
        "",
        "#if LV_COLOR_DEPTH != 16",
        f'#error "{symbol} was generated for LV_COLOR_DEPTH 16"',
        "#endif",
        "",
        f"static const uint8_t {symbol}_map[] = {{"
    ]
    
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("  " + " ".join(f"0x{b:02x}," for b in chunk))
        
    lines.extend([
        "};",
        "",
        f"const lv_img_dsc_t {symbol} = {{",
        f"  .header.cf = {cf},",
        "  .header.always_zero = 0,",
        "  .header.reserved = 0,",
        f"  .header.w = {w},",
        f"  .header.h = {h},",
        f"  .data_size = {len(data)},",
        f"  .data = {symbol}_map,",
        "};",
        ""
    ])
    return "\n".join(lines)


def angle_for(points, v):
    pts = sorted(points)
    if v <= pts[0][0]:
        return pts[0][1]
    if v >= pts[-1][0]:
        return pts[-1][1]
    for (v0, a0), (v1, a1) in zip(pts, pts[1:]):
        if v0 <= v <= v1:
            return a0 + (v - v0) / (v1 - v0) * (a1 - a0)
    return pts[-1][1]


def test_composite(dial_path, needles_meta, values, dest_path):
    face = Image.open(dial_path).convert("RGBA")
    
    for meta, val in zip(needles_meta, values):
        im_needle, px, py, pivot_x, pivot_y, pts = meta
        deg = angle_for(pts, val)
        rot_deg = -(deg + 90.0)
        
        # Create a padded canvas to rotate around (pivot_x, pivot_y)
        # Position pivot at center of rotated canvas
        dim = max(im_needle.width, im_needle.height) * 2
        canvas = Image.new("RGBA", (dim, dim), (0, 0, 0, 0))
        c_center = dim // 2
        paste_x = c_center - pivot_x
        paste_y = c_center - pivot_y
        canvas.paste(im_needle, (paste_x, paste_y))
        
        rotated = canvas.rotate(rot_deg, resample=Image.Resampling.BICUBIC)
        
        # Place rotated canvas on dial face so c_center aligns with (px, py)
        dst_x = int(round(px - c_center))
        dst_y = int(round(py - c_center))
        face.alpha_composite(rotated, (dst_x, dst_y))
        
    face.save(dest_path)
    print(f"Saved test composite to {dest_path}")


def main():
    print("Generating 360x360 needle assets...")
    
    # 1. Accum Needle & Shadow
    accu_len = ACCU["needle_len"]
    accu_boss = ACCU["boss_r"]
    accu_w = ACCU["needle_w"]
    im_accu, a_w, a_h, a_px, a_py = generate_needle(accu_len, accu_boss, accu_w, tip_w=3.2, shadow=False)
    im_accu_sh, _, _, _, _ = generate_needle(accu_len, accu_boss, accu_w, tip_w=3.2, shadow=True)
    
    im_accu.save(os.path.join(BUILD, "needle_360_accu.png"))
    im_accu_sh.save(os.path.join(BUILD, "needle_360_accu_shadow.png"))
    print(f"Accum needle: {a_w}x{a_h}, pivot ({a_px}, {a_py})")
    
    # 2. Brake Needle & Shadow
    brake_len = BRAKE_L["needle_len"]
    brake_boss = BRAKE_L["boss_r"]
    brake_w = BRAKE_L["needle_w"]
    im_brake, b_w, b_h, b_px, b_py = generate_needle(brake_len, brake_boss, brake_w, tip_w=3.2, shadow=False)
    im_brake_sh, _, _, _, _ = generate_needle(brake_len, brake_boss, brake_w, tip_w=3.2, shadow=True)
    
    im_brake.save(os.path.join(BUILD, "needle_360_brake.png"))
    im_brake_sh.save(os.path.join(BUILD, "needle_360_brake_shadow.png"))
    print(f"Brake needle: {b_w}x{b_h}, pivot ({b_px}, {b_py})")
    
    # 3. Test Composite
    dial_360_path = os.path.join(BUILD, "dial_face_360.png")
    test_meta = [
        (im_accu, ACCU["pivot"][0], ACCU["pivot"][1], a_px, a_py, ACCU["points"]),
        (im_brake, BRAKE_L["pivot"][0], BRAKE_L["pivot"][1], b_px, b_py, BRAKE_L["points"]),
        (im_brake, BRAKE_R["pivot"][0], BRAKE_R["pivot"][1], b_px, b_py, BRAKE_R["points"]),
    ]
    test_composite(dial_360_path, test_meta, [3.0, 1.0, 1.0], os.path.join(BUILD, "test_composite_360.png"))
    
    # 4. Generate gauge_geometry.h for firmware
    header_content = f"""// gauge_geometry.h - GENERATED by artwork/make_360_assets.py
// Single source of truth: artwork/build/geometry_360.json
// Angles: degrees, 0 = east, positive = clockwise, y down.
#pragma once

#include <Arduino.h>

#define DIAL_SIZE 360

// Fixed light direction shadow offset
#define SHADOW_DX {SHADOW_DX}
#define SHADOW_DY {SHADOW_DY}

// needle_accu bitmap: size and pivot inside art
#define NEEDLE_ACCU_ART_W       {a_w}
#define NEEDLE_ACCU_ART_H       {a_h}
#define NEEDLE_ACCU_ART_PIVOT_X {a_px}
#define NEEDLE_ACCU_ART_PIVOT_Y {a_py}

// needle_brake bitmap: size and pivot inside art
#define NEEDLE_BRAKE_ART_W       {b_w}
#define NEEDLE_BRAKE_ART_H       {b_h}
#define NEEDLE_BRAKE_ART_PIVOT_X {b_px}
#define NEEDLE_BRAKE_ART_PIVOT_Y {b_py}

// Accumulator
#define ACCUM_PIVOT_X    {ACCU["pivot"][0]:.1f}f
#define ACCUM_PIVOT_Y    {ACCU["pivot"][1]:.1f}f
#define ACCUM_VMIN       0.0f
#define ACCUM_VMAX       4.0f
#define ACCUM_AMIN       {ACCU["points"][0][1]:.1f}f
#define ACCUM_AMAX       {ACCU["points"][1][1]:.1f}f
#define ACCUM_NEEDLE_LEN {accu_len:.1f}f

// Brake Left (Piecewise linear: 0.0->1.2, 1.0->-46.0, 3.0->-103.0)
#define BRAKE_L_PIVOT_X    {BRAKE_L["pivot"][0]:.1f}f
#define BRAKE_L_PIVOT_Y    {BRAKE_L["pivot"][1]:.1f}f
#define BRAKE_L_VMIN       0.0f
#define BRAKE_L_VMAX       3.0f
#define BRAKE_L_NEEDLE_LEN {brake_len:.1f}f

// Brake Right (Piecewise linear: 0.0->179.0, 1.0->225.5, 3.0->283.0)
#define BRAKE_R_PIVOT_X    {BRAKE_R["pivot"][0]:.1f}f
#define BRAKE_R_PIVOT_Y    {BRAKE_R["pivot"][1]:.1f}f
#define BRAKE_R_VMIN       0.0f
#define BRAKE_R_VMAX       3.0f
#define BRAKE_R_NEEDLE_LEN {brake_len:.1f}f

struct CalPoint {{
  float val;
  float deg;
}};

static const CalPoint ACCU_POINTS[2] = {{
  {{0.0f, {ACCU["points"][0][1]:.1f}f}},
  {{4.0f, {ACCU["points"][1][1]:.1f}f}}
}};

static const CalPoint BRAKE_L_POINTS[3] = {{
  {{{BRAKE_L["points"][0][0]:.1f}f, {BRAKE_L["points"][0][1]:.1f}f}},
  {{{BRAKE_L["points"][1][0]:.1f}f, {BRAKE_L["points"][1][1]:.1f}f}},
  {{{BRAKE_L["points"][2][0]:.1f}f, {BRAKE_L["points"][2][1]:.1f}f}}
}};

static const CalPoint BRAKE_R_POINTS[3] = {{
  {{{BRAKE_R["points"][0][0]:.1f}f, {BRAKE_R["points"][0][1]:.1f}f}},
  {{{BRAKE_R["points"][1][0]:.1f}f, {BRAKE_R["points"][1][1]:.1f}f}},
  {{{BRAKE_R["points"][2][0]:.1f}f, {BRAKE_R["points"][2][1]:.1f}f}}
}};

inline float interpolate_gauge_angle(float val, const CalPoint* pts, int count) {{
  if (val <= pts[0].val) return pts[0].deg;
  if (val >= pts[count - 1].val) return pts[count - 1].deg;
  for (int i = 0; i < count - 1; ++i) {{
    if (val >= pts[i].val && val <= pts[i + 1].val) {{
      float t = (val - pts[i].val) / (pts[i + 1].val - pts[i].val);
      return pts[i].deg + t * (pts[i + 1].deg - pts[i].deg);
    }}
  }}
  return pts[count - 1].deg;
}}
"""
    geom_dest = os.path.join(FW_DEST, "gauge_geometry.h")
    with open(geom_dest, "w", encoding="utf-8") as f:
        f.write(header_content)
    print(f"Wrote {geom_dest}")
    
    # 5. Convert PNGs to LVGL C arrays
    lvgl_jobs = [
        (dial_360_path, "img_dial_face", False, "360x360 dial face"),
        (os.path.join(BUILD, "needle_360_accu.png"), "img_needle_accu", True, "Accumulator pointer"),
        (os.path.join(BUILD, "needle_360_accu_shadow.png"), "img_needle_accu_shadow", True, "Accumulator shadow"),
        (os.path.join(BUILD, "needle_360_brake.png"), "img_needle_brake", True, "Brake pointer"),
        (os.path.join(BUILD, "needle_360_brake_shadow.png"), "img_needle_brake_shadow", True, "Brake shadow"),
    ]
    
    for src_path, sym, alpha, comment in lvgl_jobs:
        im = Image.open(src_path).convert("RGBA")
        c_code = convert_to_lvgl_c(im, sym, alpha, comment)
        dest_c = os.path.join(FW_DEST, sym + ".c")
        with open(dest_c, "w", encoding="utf-8") as f:
            f.write(c_code)
        print(f"Wrote {sym}.c ({im.size[0]}x{im.size[1]})")

    print("\nAll 360 assets and LVGL C arrays generated successfully!")


if __name__ == "__main__":
    main()