#!/usr/bin/env python3
"""Convert the generated PNGs into LVGL image descriptors.

Targets LVGL 8 with LV_COLOR_DEPTH 16, which is what the ESP32 round-LCD
board packages ship with. For LVGL 9 use its own lv_image_dsc_t layout
instead - the pixel data is identical, only the struct changed.

    python to_lvgl.py

Writes build/img_*.c, ready to drop next to the sketch.

Colour formats:
    dial face  TRUE_COLOR         2 bytes/px, opaque, lives in flash
    needles    TRUE_COLOR_ALPHA   3 bytes/px, needs the alpha to rotate
                                  cleanly over the face
"""

import os

from PIL import Image

import make_dial as md

OUT = md.OUT

JOBS = [
    ("dial_face.png", "img_dial_face", False),
    ("needle_accu.png", "img_needle_accu", True),
    ("needle_brake.png", "img_needle_brake", True),
    ("needle_accu_shadow.png", "img_needle_accu_shadow", True),
    ("needle_brake_shadow.png", "img_needle_brake_shadow", True),
]


def rgb565(r, g, b) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def convert(png_path: str, symbol: str, alpha: bool) -> str:
    im = Image.open(png_path).convert("RGBA")
    w, h = im.size
    px = im.load()

    data = bytearray()
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if not alpha:
                # Composite onto black so the opaque face has no fringe.
                r = r * a // 255
                g = g * a // 255
                b = b * a // 255
            c = rgb565(r, g, b)
            data.append(c & 0xFF)          # LVGL expects little endian
            data.append((c >> 8) & 0xFF)
            if alpha:
                data.append(a)

    cf = "LV_IMG_CF_TRUE_COLOR_ALPHA" if alpha else "LV_IMG_CF_TRUE_COLOR"

    lines = []
    lines.append("// GENERATED by art/to_lvgl.py from %s - do not edit."
                 % os.path.basename(png_path))
    lines.append("#include <lvgl.h>")
    lines.append("")
    lines.append("#if LV_COLOR_DEPTH != 16")
    lines.append('#error "%s was generated for LV_COLOR_DEPTH 16"' % symbol)
    lines.append("#endif")
    lines.append("")
    lines.append("static const uint8_t %s_map[] = {" % symbol)

    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("  " + " ".join("0x%02x," % b for b in chunk))
    lines.append("};")
    lines.append("")
    lines.append("const lv_img_dsc_t %s = {" % symbol)
    lines.append("  .header.cf = %s," % cf)
    lines.append("  .header.always_zero = 0,")
    lines.append("  .header.reserved = 0,")
    lines.append("  .header.w = %d," % w)
    lines.append("  .header.h = %d," % h)
    lines.append("  .data_size = %d," % len(data))
    lines.append("  .data = %s_map," % symbol)
    lines.append("};")
    lines.append("")

    return "\n".join(lines), len(data), w, h


def main():
    total = 0
    for png, symbol, alpha in JOBS:
        src = os.path.join(OUT, png)
        if not os.path.exists(src):
            print("missing %s - run make_dial.py first" % png)
            continue
        text, size, w, h = convert(src, symbol, alpha)
        dest = os.path.join(OUT, symbol + ".c")
        with open(dest, "w", encoding="utf-8") as fh:
            fh.write(text)
        total += size
        print("%-22s %3dx%-3d  %7d bytes -> %s"
              % (png, w, h, size, os.path.basename(dest)))
    print("total image data: %.0f KB of flash" % (total / 1024.0))


if __name__ == "__main__":
    main()
