// accu_panel.ino
// A320 accumulator + brake pressure triple indicator.
// SimDeck module #1.
//
// Board:      ESP32-S3 with a 480x480 round LCD (Waveshare
//             ESP32-S3-Touch-LCD-2.1 or equivalent ST7701 panel).
// Partition:  MUST have two app slots. Pick any scheme whose name mentions
//             OTA, or "Minimal SPIFFS". "Huge APP" will not update.
//
// Geometry comes from gauge_geometry.h, generated by art/make_dial.py.
// Change the dial there and both the artwork and these angles move together.

#include <Arduino.h>
#include <WiFi.h>
#include <lvgl.h>
#include <math.h>

#include "SimDeckClient.h"
#include "gauge_geometry.h"

// ---------------------------------------------------------------- identity

#define FW_VERSION  "1.0.0"
#define MODULE_ID   "accu-01"        // unique per board
#define MODULE_TYPE "accu_panel"     // matches the firmware manifest key

static const char* WIFI_SSID = "YOUR_SSID";
static const char* WIFI_PASS = "YOUR_PASSWORD";

// Logical names. Slot order here == slot order assigned by the hub.
static const char* const SUBS[] = {
    "brake.accum_psi",   // slot 0
    "brake.left_psi",    // slot 1
    "brake.right_psi",   // slot 2
};
static const uint8_t SUB_COUNT = 3;

SimDeckClient hub;

// -------------------------------------------------------------- needles

struct Needle {
  lv_obj_t* img;
  lv_obj_t* shadow;
  const lv_img_dsc_t* art;
  const lv_img_dsc_t* shadowArt;
  int16_t artPivotX, artPivotY;   // from gauge_geometry.h
  int16_t pivotX, pivotY;
  float minVal, maxVal;      // in psi
  float minAngle, maxAngle;  // degrees, 0 = east, clockwise, y down
  float smoothing;           // per frame; lower = heavier pointer
  float shown;
};

// The dial is drawn in thousands of psi; the wire carries raw psi.
#define K 1000.0f

static Needle nAccum = {
    nullptr, nullptr, nullptr, nullptr, NEEDLE_ACCU_ART_PIVOT_X, NEEDLE_ACCU_ART_PIVOT_Y,
    (int16_t)ACCUM_PIVOT_X, (int16_t)ACCUM_PIVOT_Y,
    ACCUM_VMIN * K, ACCUM_VMAX * K, ACCUM_AMIN, ACCUM_AMAX, 0.12f, 0.0f};

static Needle nLeft = {
    nullptr, nullptr, nullptr, nullptr, NEEDLE_BRAKE_ART_PIVOT_X, NEEDLE_BRAKE_ART_PIVOT_Y,
    (int16_t)BRAKE_L_PIVOT_X, (int16_t)BRAKE_L_PIVOT_Y,
    BRAKE_L_VMIN * K, BRAKE_L_VMAX * K, BRAKE_L_AMIN, BRAKE_L_AMAX, 0.16f, 0.0f};

static Needle nRight = {
    nullptr, nullptr, nullptr, nullptr, NEEDLE_BRAKE_ART_PIVOT_X, NEEDLE_BRAKE_ART_PIVOT_Y,
    (int16_t)BRAKE_R_PIVOT_X, (int16_t)BRAKE_R_PIVOT_Y,
    BRAKE_R_VMIN * K, BRAKE_R_VMAX * K, BRAKE_R_AMIN, BRAKE_R_AMAX, 0.16f, 0.0f};

// Artwork from art/build/*.png, converted to LVGL C arrays.
// The needle bitmaps point straight up with the pivot at the bottom centre.
LV_IMG_DECLARE(img_dial_face);
LV_IMG_DECLARE(img_needle_accu);
LV_IMG_DECLARE(img_needle_brake);
LV_IMG_DECLARE(img_needle_accu_shadow);
LV_IMG_DECLARE(img_needle_brake_shadow);

// Shadows cost a second rotated image per pointer. Set to 0 if the frame
// rate suffers - the panel still reads correctly without them.
#define USE_SHADOWS 1

static lv_obj_t* faceObj;
static lv_obj_t* statusDot;
static uint32_t identifyUntil = 0;

// ---------------------------------------------------------------- helpers

static void needleInitShadow(Needle& n, const lv_img_dsc_t* shadowArt) {
#if USE_SHADOWS
  n.shadowArt = shadowArt;
  n.shadow = lv_img_create(lv_scr_act());
  lv_img_set_src(n.shadow, shadowArt);
  lv_img_set_pivot(n.shadow, n.artPivotX, n.artPivotY);
  lv_obj_set_pos(n.shadow,
                 n.pivotX - n.artPivotX + SHADOW_DX,
                 n.pivotY - n.artPivotY + SHADOW_DY);
  lv_img_set_antialias(n.shadow, true);
#endif
}

static void needleInit(Needle& n, const lv_img_dsc_t* art) {
  n.art = art;
  n.img = lv_img_create(lv_scr_act());
  lv_img_set_src(n.img, art);

  // The pivot sits inside the art with the tail behind it, so the distance
  // from pivot to tip equals the scale's needle length exactly.
  lv_img_set_pivot(n.img, n.artPivotX, n.artPivotY);
  lv_obj_set_pos(n.img, n.pivotX - n.artPivotX, n.pivotY - n.artPivotY);
  lv_img_set_antialias(n.img, true);
  n.shown = n.minVal;
}

static void needleUpdate(Needle& n, float target) {
  if (isnan(target)) return;
  if (target < n.minVal) target = n.minVal;
  if (target > n.maxVal) target = n.maxVal;

  // First-order smoothing so the pointer glides instead of teleporting.
  n.shown += (target - n.shown) * n.smoothing;

  float t = (n.shown - n.minVal) / (n.maxVal - n.minVal);
  float deg = n.minAngle + t * (n.maxAngle - n.minAngle);

  // Art points up; LVGL rotates clockwise in 0.1 degree units.
  int16_t a = (int16_t)lroundf((deg + 90.0f) * 10.0f);
  lv_img_set_angle(n.img, a);
#if USE_SHADOWS
  if (n.shadow) lv_img_set_angle(n.shadow, a);
#endif
}

static void onIdentify() { identifyUntil = millis() + 4000; }

// ------------------------------------------------------------------- ui

static void buildUi() {
  lv_obj_t* scr = lv_scr_act();
  lv_obj_set_style_bg_color(scr, lv_color_black(), 0);

  faceObj = lv_img_create(scr);
  lv_img_set_src(faceObj, &img_dial_face);
  lv_obj_center(faceObj);

  // All shadows first, then all pointers, so one pointer's shadow can
  // never land on top of another pointer.
  needleInitShadow(nAccum, &img_needle_accu_shadow);
  needleInitShadow(nLeft, &img_needle_brake_shadow);
  needleInitShadow(nRight, &img_needle_brake_shadow);

  needleInit(nAccum, &img_needle_accu);
  needleInit(nLeft, &img_needle_brake);
  needleInit(nRight, &img_needle_brake);

  // Small link indicator, bottom of the dial. Dim when there is no data,
  // which is far easier to diagnose at a glance than frozen needles.
  statusDot = lv_obj_create(scr);
  lv_obj_set_size(statusDot, 8, 8);
  lv_obj_set_style_radius(statusDot, 4, 0);
  lv_obj_set_style_border_width(statusDot, 0, 0);
  lv_obj_align(statusDot, LV_ALIGN_CENTER, 0, 214);
}

static void updateStatusDot() {
  lv_color_t c;
  if (hub.updating())      c = lv_palette_main(LV_PALETTE_AMBER);
  else if (hub.live())     c = lv_color_hex(0x123018);   // barely visible
  else if (hub.linked())   c = lv_palette_main(LV_PALETTE_AMBER);
  else                     c = lv_palette_main(LV_PALETTE_RED);

  if (millis() < identifyUntil && (millis() / 200) % 2)
    c = lv_color_white();

  lv_obj_set_style_bg_color(statusDot, c, 0);
}

// ----------------------------------------------------------------- boot

void setup() {
  Serial.begin(115200);

  // ---- board display bring-up goes here ----
  // Panel init + lv_init() + LVGL tick/flush hooks, from your board's BSP.

  buildUi();

  WiFi.mode(WIFI_STA);
  WiFi.setSleep(false);          // sleep adds tens of ms of jitter
  WiFi.begin(WIFI_SSID, WIFI_PASS);
  Serial.print("wifi");
  while (WiFi.status() != WL_CONNECTED) {
    delay(250);
    Serial.print(".");
  }
  Serial.printf("\nip %s  fw %s\n", WiFi.localIP().toString().c_str(),
                FW_VERSION);

  hub.onIdentify(onIdentify);
  hub.begin(MODULE_ID, MODULE_TYPE, "Accumulator/Brake Panel", FW_VERSION,
            SUBS, SUB_COUNT, 30.0f);
}

void loop() {
  hub.poll();

  if (!hub.updating()) {
    float accum = hub.value(0);
    float left = hub.value(1);
    float right = hub.value(2);

    if (!hub.live()) {
      // Sim gone or hub down: drive to zero rather than freezing mid-scale,
      // which reads as a working instrument showing a real pressure.
      accum = left = right = 0.0f;
    }

    needleUpdate(nAccum, accum);
    needleUpdate(nLeft, left);
    needleUpdate(nRight, right);
  }

  updateStatusDot();
  lv_timer_handler();
  delay(5);
}
