// gauge_geometry.h - GENERATED by art/make_dial.py, do not edit.
//
// Angles: degrees, 0 = east, positive = clockwise, y down.
#pragma once

#define DIAL_SIZE 480

// fixed light direction: shadow offset in screen pixels
#define SHADOW_DX 4
#define SHADOW_DY 5

// needle_accu bitmap: pivot position inside the art
#define NEEDLE_ACCU_ART_W       25
#define NEEDLE_ACCU_ART_H       99
#define NEEDLE_ACCU_ART_PIVOT_X 12
#define NEEDLE_ACCU_ART_PIVOT_Y 97

// needle_brake bitmap: pivot position inside the art
#define NEEDLE_BRAKE_ART_W       25
#define NEEDLE_BRAKE_ART_H       67
#define NEEDLE_BRAKE_ART_PIVOT_X 12
#define NEEDLE_BRAKE_ART_PIVOT_Y 65

// accum
#define ACCUM_PIVOT_X   240.0f
#define ACCUM_PIVOT_Y   123.0f
#define ACCUM_VMIN      0.0f
#define ACCUM_VMAX      4.0f
#define ACCUM_AMIN      131.0f
#define ACCUM_AMAX      49.0f
#define ACCUM_NEEDLE_LEN 96.0f

// brake_l
#define BRAKE_L_PIVOT_X   143.0f
#define BRAKE_L_PIVOT_Y   313.0f
#define BRAKE_L_VMIN      0.0f
#define BRAKE_L_VMAX      3.0f
#define BRAKE_L_AMIN      8.0f
#define BRAKE_L_AMAX      -112.0f
#define BRAKE_L_NEEDLE_LEN 64.0f

// brake_r
#define BRAKE_R_PIVOT_X   337.0f
#define BRAKE_R_PIVOT_Y   313.0f
#define BRAKE_R_VMIN      0.0f
#define BRAKE_R_VMAX      3.0f
#define BRAKE_R_AMIN      172.0f
#define BRAKE_R_AMAX      292.0f
#define BRAKE_R_NEEDLE_LEN 64.0f
